### ISSUE TITLE
xueshanf/docker-s3fs and Mac OS X

### ISSUE THREAD

**Issue by bjornharvold** [xueshanf/docker-s3fs#11]
Hi,

Thank you for creating this Docker image.

I am wondering specifically if this works for testing in a Mac OS X environment. I'm running Docker 1.12.x and I've followed all your instructions. But I do get a failure when I try to run it. 

Here's the error:

```
=> docker-compose up -d
Starting s3fs_s3fs_1

ERROR: for s3fs  Cannot start service s3fs: linux mounts: Path /mnt/mydata is mounted on /mnt/mydata but it is not a shared mount.
ERROR: Encountered errors while bringing up the project.
```

I have created that directory on my Mac and I have shared it with Docker using the File Sharing tab in the Docker Mac OS X app.

Please advise and thank you,
Bjorn

**Comment by xueshanf** [comment]
@bjornharvold I haven't tested on Mac OS before but I just did yesterday. I tried to use bindfs and shared it in Docker for Mac. I ended up with the same errors as you did. Yeah, I could not make it work on Mac. 
It seems that the s3fs package will work on Mac OS without container. Would that be an option for you? I will continue to research s3fs container on Mac when I have chances.

**Comment by bjornharvold** [comment]
Thank you for getting back to me. It works fine on Ubuntu and it's something I am talking to Bitbucket.com about to use with their Pipelines product. Would be great to have externalized persistent storage for large builds that require a lot of dependencies.

Thank you for making this,
Bjorn

**Comment by byer0021** [comment]
Out of curiosity, was there ever an OS X solution found that leverages the container?

**Comment by xueshanf** [comment]
@byer0021 I tried recently and the s3fs container still doesn't work Docker for Mac as docker engine.

**Comment by byer0021** [comment]
Thank you @xueshanf . I assume it'd be a challenge since it actually would be mounting on the linux host used by Docker for Mac.
