### ISSUE TITLE
s3fs vs s3ql

### ISSUE THREAD

**Issue by joelchen** [xueshanf/docker-s3fs#2]
Hi XueShan,

Could you share your experience with s3fs and s3ql? Thank you.

Warmest Regards,
Joel

**Comment by xueshanf** [comment]
We use s3ql for our private git lab backend storage but both gitlab and s3ql are running as processes on an EC2  Linux host, not as docker containers. Haven't used them inside of a container to provide backend for other services in the same container yet. 

We were using s3fs for a while and switched to s3ql for unlimited file size. I also felt that s3ql seems have better performance, but take it as a grain of salt. We haven't run any bench-mark against the two filesystems.  

What I liked s3fs is you can use  other s3 tool to manage individual files, while for s3ql, you have to use s3ql. 

BTW, for  file sharing (mostly for code and configurations, not for real time data) among containers, we use an awscli s3 sync container (xueshanf/awscli) to  sync a shared s3 bucket to EC2 hosts. A cheap way to have a 'centralized' file system.

Xueshan

**Comment by joelchen** [comment]
Hi Xueshan,

Thanks for your sharing for experience with these 2 S3 filesystems. The s3fs died in my container, and I could not find any logs to understand the cause of it to take any action, so I am thinking of using another S3 filesystem.

Discovered [riofs](https://github.com/skoobe/riofs), but have not decided to try it because the project is not as active as s3fs, although [someone](https://github.com/skoobe/riofs/issues/76) claims that riofs is faster than s3fs.

Warmest Regards,
Joel

**Comment by xueshanf** [comment]
FYI: take a look at the new README.md in this repo. Docker 1.10 supports host volume share that make it possible to use s3fs container's file system on host.
