### ISSUE TITLE
S3 fails to mount using this Dockerfile

### ISSUE THREAD

**Issue by brspurri** [xueshanf/docker-s3fs#3]
Hi there,

I am trying to use your Dockerfile to mount my S3 bucket to my filesystem, however, I am running into an error:

```
s3fs mys3bucket /mnt/
fuse: failed to open /dev/fuse: Operation not permitted
```

Any ideas what could be causing this? The docker image build went smoothly.

**Comment by xueshanf** [comment]
Works for me, with:

```
 docker run --rm --cap-add mknod --cap-add sys_admin --device=/dev/fuse -it xueshanf/s3fs
```

Here is my docker version:
core@n1 ~ $ docker --version
Docker version 1.4.1, build 5bc2ff8-dirty

Maybe your docker version is older? If you replace  --cap-add mknod --cap-add sys_admin with --privileged, does it work?

**Comment by brspurri** [comment]
I'm using this on AWS Elastic Beanstalk, and it appears that AWS forms their own `run` command, which was leading to my actual issue. I'm closing this now, but if I find a solution, I'll post it for others running into similar issues.

**Comment by avinash-13** [comment]
hii,
i tried your dockerfile ....but getting an error
error: s3fs: TRANSPORT ENDPOINT  NOT CONNECTED

**Comment by xueshanf** [comment]
@avinash-13 did you happen to include s3:// in the bucket name when you started docker run ...?
The bucket name should be just the name of bucket without s3:// in front of it.
