### ISSUE TITLE
use docker-s3fs behind a proxy

### ISSUE THREAD

**Issue by yren** [xueshanf/docker-s3fs#5]
My env behind a proxy, I try to mount s3 bucket using, 
export http_proxy=http://proxy.internal:3128
/usr/bin/s3fs -o passwd_file=/root/.s3fs -o allow_other -o use_cache=/tmp -o connect_timeout=10   mybucketname /mnt/mybucket

but meet an error like:
fuse: failed to exec fusermount: No such file or directory

Do you have any advise on this, thanks.

**Comment by xueshanf** [comment]
Make sure the mount point '/mnt/mybucket' directory exist, e.g. "mkdir -p /mnt/mybucket'. Do this inside of the container.

**Comment by yren** [comment]
Thanks for reply.
Yeah, the mount point exist. Actually I can mount s3 success when docker container can directly access internet, but when behind a proxy I meet this error, "fuse: failed to exec fusermount: No such file or directory". Even though I export http_proxy.  Any suggestion.

**Comment by yren** [comment]
Some one answered this question on another thread, adding --privileged to docker run can resolve this. Thanks.

**Comment by xueshanf** [comment]
Good to know. I wonder, if you start the container like so, without using --privileged option, but keep the --cap-add options,  will it work?

```
docker run -e HTTP_PROXY=http://proxy.internal:3128  --rm --cap-add mknod --cap-add sys_admin --device=/dev/fuse -it xueshanf/s3fs
```

**Comment by xueshanf** [comment]
or add  "--cap-add  NET_ADMIN" in docker run command  should work. I'd like to document this so we only give the container necessary privileges.

**Comment by yren** [comment]
I tried use "--cap-add NET_ADMIN" in docker run, but still not work. I guess container may need other Linux capabilities. My docker run like below

```
docker run -p 80:80 --rm -e http_proxy=http://proxy.internal:3128 --cap-add NET_ADMIN --cap-add mknod --cap-add sys_admin --device=/dev/fuse -it  myimage:0.1
```

**Comment by xueshanf** [comment]
@yren thanks for letting me know. Looks like --privileged solves your problem. I was hoping to find the right capability, but oh well :)
