### ISSUE TITLE
s3fs and ECS

### ISSUE THREAD

**Issue by itajaja** [xueshanf/docker-s3fs#6]
I'd like to use this image on ECS, have you ever tried it? Are there any caveats you are aware of? Thanks!

**Comment by xueshanf** [comment]
@itajaja I haven't tried it in ECS containers but I did tested  it on CoreOS with Gitlab container, with s3fs as backend for repository. It's very slow.  By comparison, using it on EC2 directly without container the performance is acceptable.

**Comment by itajaja** [comment]
thanks for the insight :)
