### ISSUE TITLE
FUSE error with command from README (caused by apparmor)

### ISSUE THREAD

**Issue by philicious** [xueshanf/docker-s3fs#8]
Hey again,
so I tried out your image and its nearly perfect. Just a little sth missing in README:

the correct and required security options for NOT needing `--privileged` are 

```
--cap-add mknod --cap-add sys_admin --security-opt apparmor:unconfined
```

Without the apparmor stuff, you get 

```
fuse: mount failed: Permission denied
```

Referenes:
https://github.com/docker/docker/issues/16429
https://github.com/docker/docker/issues/9448

**Comment by xueshanf** [comment]
Updated the doc (also tested on CoreOS which doesn't have apparmor installed at all). Thanks!
